### ISSUE TITLE
setup new react theme

### ISSUE THREAD

**Issue by tmeralus** [1019-Studios/1019studios.org#17]

**Comment by tmeralus** [comment]
There is a compressed zip file holding the theme and content for the ielectro solutions website. unzip that folder. delete the zipped folder and test that the theme works with the working version of nodejs or npm installed on your computer. 
Update the readme file to add the stable nodejs version and important packages needed for this project (if they are not already in the README file).

**Comment by Sylar-codex** [comment]
Please where can I find the compressed zip file?

**Comment by tmeralus** [comment]
this has been completed. We just havent merged it.
